### PR TITLE
Fix a few compilation issues (clang 13)

### PR DESCRIPTION
**Pull request by stilllman**
This PR fixes a few compilation errors I had when compiling `orc` with Clang 13.0:

- missing includes
- `std::ios_base::beg` prefixed with enum name
- namespace `log` conflicting with `log` from `math.h`

## How Has This Been Tested?

The code now compiles with clang 13.0, but I haven't checked if it still compiles with Xcode. The `orc_test` executable runs correctly (but fails because of incorrect binary file format of course).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by fosterbrereton — APPROVED** [review]
These LGTM. Thank you for helping keep ORC alive for the next generation of Clang.
